import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: 1,
    name: "Chocolate Truffle Cake",
    price: 25.99,
    imageUrl:
      "https://images.pexels.com/photos/4109998/pexels-photo-4109998.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    altText: "Chocolate Truffle Cake",
    rating: 4.5,
    category: "Cake",
    subcategory: "Chocolate",
    bestseller: true,
  },
  {
    _id: 2,
    name: "Vanilla Celebration Cake",
    price: 29.99,
    imageUrl:
      "https://images.pexels.com/photos/1721932/pexels-photo-1721932.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    altText: "Vanilla Celebration Cake",
    rating: 4.8,
    category: "Cake",
    subCategory: "Vanilla",
    bestseller: true,
  },
  {
    _id: 3,
    name: "Red Velvet Cupcakes",
    price: 19.99,
    imageUrl:
      "https://images.pexels.com/photos/6375498/pexels-photo-6375498.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    altText: "Red Velvet Cupcakes",
    rating: 4.6,
    category: "Cake",
    subCategory: "Red Velvet",
    bestseller: false,
  },
  {
    _id: 4,
    name: "Rainbow Cake",
    price: 49.99,
    imageUrl:
      "https://images.pexels.com/photos/11753321/pexels-photo-11753321.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    altText: "Rainbow Cake",
    rating: 4.9,
    category: "Cake",
    subCategory: "Specialty Cake",
    bestseller: true,
  },
  {
    _id: 5,
    name: "Black Forest Cake",
    price: 34.99,
    imageUrl:
      "https://images.pexels.com/photos/6341564/pexels-photo-6341564.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Black Forest Cake",
    rating: 4.6,
    category: "Cake",
    subCategory: "Chocolate Cake",
    bestseller: false,
  },
  {
    _id: 6,
    name: "Cheesecake Sampler",
    price: 39.99,
    imageUrl:
      "https://images.pexels.com/photos/15419532/pexels-photo-15419532/free-photo-of-a-cheesecake-with-caramel-on-top.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Cheesecake Sampler",
    rating: 4.7,
    category: "Cake",
    subCategory: "Cheesecake",
    bestseller: true,
  },
  {
    _id: 7,
    name: "Carrot Cake",
    price: 24.99,
    imageUrl:
      "https://images.pexels.com/photos/2612373/pexels-photo-2612373.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Carrot Cake",
    rating: 4.4,
    category: "Cake",
    subCategory: "Carrot",
    bestseller: false,
  },
  {
    _id: 8,
    name: "Triple Chocolate Cake",
    price: 39.99,
    imageUrl:
      "https://images.pexels.com/photos/15445807/pexels-photo-15445807/free-photo-of-close-up-of-a-chocolate-cake.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Triple Chocolate Cake",
    rating: 4.7,
    category: "Cake",
    subCategory: "Chocolate Cake",
    bestseller: true,
  },
  {
    _id: 9,
    name: "Cheesecake Brownies",
    price: 19.99,
    imageUrl:
      "https://images.pexels.com/photos/4078187/pexels-photo-4078187.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Cheesecake Brownies",
    rating: 4.6,
    category: "Cake",
    subCategory: "Brownies",
    bestseller: false,
  },
  {
    _id: 10,
    name: "Classic Chocolate Cake",
    price: 39.99,
    imageUrl:
      "https://images.pexels.com/photos/15464829/pexels-photo-15464829/free-photo-of-close-up-of-chocolate-cake.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    altText: "Classic Chocolate Cake",
    rating: 4.7,
    category: "Cake",
    subCategory: "Chocolate",
    bestseller: true,
  },
  {
    _id: 11,
    name: "Strawberry Shortcake",
    price: 29.99,
    imageUrl:
      "https://images.pexels.com/photos/15471971/pexels-photo-15471971/free-photo-of-white-cream-with-strawberries.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Strawberry Shortcake",
    rating: 4.5,
    category: "Cake",
    subCategory: "Strawberry",
    bestseller: false,
  },
  {
    _id: 12,
    name: "Red Velvet Cake",
    price: 34.99,
    imageUrl:
      "https://images.pexels.com/photos/806363/pexels-photo-806363.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Red Velvet Cake",
    rating: 4.3,
    category: "Cake",
    subCategory: "Red Velvet",
    bestseller: true,
  },
  {
    _id: 13,
    name: "Vanilla Pound Cake",
    price: 24.99,
    imageUrl:
      "https://images.pexels.com/photos/5610353/pexels-photo-5610353.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Vanilla Pound Cake",
    rating: 4.9,
    category: "Cake",
    subCategory: "Vanilla",
    bestseller: true,
  },
  {
    _id: 14,
    name: "Classic Vanilla Cake",
    price: 49.99,
    imageUrl:
      "https://images.pexels.com/photos/1038711/pexels-photo-1038711.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    altText: "Classic Vanilla Cake",
    rating: 4.8,
    category: "Cake",
    subCategory: "Vanilla",
    bestseller: true,
  },
  {
    _id: 15,
    name: "Chocolate Fudge Cake",
    price: 39.99,
    imageUrl:
      "https://images.pexels.com/photos/8732739/pexels-photo-8732739.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Chocolate Fudge Cake",
    rating: 4.7,
    category: "Cake",
    subCategory: "Chocolate",
    bestseller: false,
  },
  {
    _id: 16,
    name: "Lemon Poppy Seed Cake",
    price: 29.99,
    imageUrl:
      "https://images.pexels.com/photos/264939/pexels-photo-264939.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Lemon Poppy Seed Cake",
    rating: 4.6,
    category: "Cake",
    subCategory: "Lemon",
    bestseller: false,
  },
  {
    _id: 17,
    name: "Marble Pound Cake",
    price: 34.99,
    imageUrl:
      "https://images.pexels.com/photos/7235675/pexels-photo-7235675.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Marble Pound Cake",
    rating: 4.4,
    category: "Cake",
    subCategory: "Marble",
    bestseller: true,
  },
  {
    _id: 18,
    name: "Salted Caramel Cake",
    price: 39.99,
    imageUrl:
      "https://images.pexels.com/photos/15772706/pexels-photo-15772706/free-photo-of-close-up-of-cake-with-decoration.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Salted Caramel Cake",
    rating: 4.7,
    category: "Cake",
    subCategory: "Salted Caramel",
    bestseller: false,
  },
  {
    _id: 19,
    name: "Mango Mousse Cake",
    price: 49.99,
    imageUrl:
      "https://images.pexels.com/photos/140831/pexels-photo-140831.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Mango Mousse Cake",
    rating: 4.5,
    category: "Cake",
    subCategory: "Mango Mousse",
    bestseller: true,
  },
  {
    _id: 20,
    name: "Raspberry Chocolate Cake",
    price: 34.99,
    imageUrl:
      "https://images.pexels.com/photos/6133334/pexels-photo-6133334.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Raspberry Chocolate Cake",
    rating: 4.8,
    category: "Cake",
    subCategory: "Raspberry Chocolate",
    bestseller: false,
  },
  {
    _id: 21,
    name: "Coconut Cream Cake",
    price: 29.99,
    imageUrl:
      "https://images.pexels.com/photos/3992134/pexels-photo-3992134.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Coconut Cream Cake",
    rating: 4.3,
    category: "Cake",
    subCategory: "Coconut Cream",
    bestseller: true,
  },

  {
    _id: 22,
    name: "Money Tree",
    price: 29.99,
    imageUrl:
      "https://www.fnp.com/images/pr/l/v20230404060442/money-plant-in-colourfull-rajwada-printed-pot-hand-delivery_3.jpg",
    altText: "Money Tree",
    rating: 4.7,
    category: "Plant",
    subCategory: "Indoor",
    bestseller: true,
  },
  {
    _id: 23,
    name: "Jade Plant",
    price: 24.99,
    imageUrl:
      "https://www.fnp.com/images/pr/l/v20230406050253/jade-plant-in-vibrant-floral-pot_1.jpg",
    altText: "Jade Plant",
    rating: 4.5,
    category: "Plant",
    subCategory: "Indoor",
    bestseller: false,
  },
  {
    _id: 24,
    name: "Snake Plant",
    price: 19.99,
    imageUrl:
      "https://www.fnp.com/images/pr/l/v20230328085218/greeny-sansevieria-snake-plant_1.jpg",
    altText: "Snake Plant",
    rating: 4.4,
    category: "Plant",
    subCategory: "Indoor",
    bestseller: true,
  },
  {
    _id: 25,
    name: "Bonsai Plant",
    price: 34.99,
    imageUrl:
      "https://www.fnp.com/images/pr/l/v20180804103038/desert-rose-adenium-plant_1.jpg",
    altText: "Bonsai",
    rating: 4.6,
    category: "Plant",
    subCategory: "Indoor",
    bestseller: false,
  },
  {
    _id: 26,
    name: "Bamboo Palm",
    price: 27.99,
    imageUrl:
      "https://www.fnp.com/images/pr/l/v20211109104020/bringing-good-luck-standard_1.jpg",
    altText: "Bamboo Palm",
    rating: 4.3,
    category: "Plant",
    subCategory: "Indoor",
    bestseller: true,
  },

  {
    _id: 27,
    name: "Roses",
    price: 12.99,
    imageUrl:
      "https://www.fnp.com/images/pr/l/v20190122180449/mixed-roses-romantic-bunch_1.jpg",
    altText: "Roses",
    rating: 4.5,
    category: "Flower",
    subCategory: "Rose",
    bestseller: true,
  },
  {
    _id: 28,
    name: "Lilies",
    price: 9.99,
    imageUrl:
      "https://www.fnp.com/images/pr/l/v20221006132320/blooming-asiatic-lilies-in-black-ribbon-tied-vase_1.jpg",
    altText: "Lilies",
    rating: 4.3,
    category: "Flower",
    subCategory: "Lily",
    bestseller: false,
  },
  {
    _id: 29,
    name: "Daisies",
    price: 7.99,
    imageUrl:
      "https://www.fnp.com/images/pr/l/v20210629103556/magic-of-love-floral-arrangement_1.jpg",
    altText: "Daisies",
    rating: 4.1,
    category: "Flower",
    subCategory: "Daisy",
    bestseller: true,
  },
  {
    _id: 30,
    name: "Orchids",
    price: 14.99,
    imageUrl:
      "https://www.fnp.com/images/pr/l/v20220706124748/enchanting-orchids-bouquet_1.jpg",
    altText: "Orchids",
    rating: 4.4,
    category: "Flower",
    subCategory: "Orchid",
    bestseller: false,
  },
  {
    _id: 31,
    name: "Sunflowers",
    price: 11.99,
    imageUrl:
      "https://images.pexels.com/photos/9168324/pexels-photo-9168324.jpeg?auto=compress&cs=tinysrgb&w=600",
    altText: "Sunflowers",
    rating: 4.2,
    category: "Flower",
    subCategory: "Sunflower",
    bestseller: true,
  },
];
